name: Lint and Format Check (Rust)
env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable
  RUST_TOOLCHAIN_NIGHTLY: nightly
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_NIGHTLY}}
          components: clippy, rustfmt

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Formatting
        run: |
          cd rust
          cargo +nightly fmt --all -- --check

      - name: Run Clippy
        run: |
          cd rust
          cargo clippy -- -D warnings
