name: Lint and Format Check (Typescript)

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.14"
                  cache: "yarn"
                  cache-dependency-path: ./ts/yarn.lock

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                  cd ts
                  yarn install --frozen-lockfile

            - name: Formatting and linting the project
              run: |
                  cd ts
                  yarn lint
