name: Publish to Crates.io
env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

on:
  push:
    branches: ["main"]
    tags: ["v*"] # Trigger the workflow on version tags (e.g., v1.0.0)

jobs:
  publish:
    name: Publish Rust crate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "RUST_TOOLCHAIN=${{env.RUST_TOOLCHAIN}}"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Dry-run publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd rust
          cargo publish --dry-run --all-features --verbose
