name: Publish to npmjs

# Trigger the workflow only on version tags (e.g., v1.0.0)
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish Typescript package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14"

      - name: Install Dependencies
        run: |
          cd ts
          yarn install --frozen-lockfile

      - name: Dry-run publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
        run: |
          cd ts
          npm publish --dry-run
