name: Publish to Crates.io

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

# Trigger the workflow only on version tags (e.g., v1.0.0)
# on:
#   push:
#     tags:
#       - "v*"

jobs:
  publish:
    name: Publish Rust crate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Dry-run publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd rust
          cargo publish --dry-run --all-features --verbose
