name: Semantic PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which scopes are allowed (newline-delimited).
          # TODO: Add more scope here based on project structure.
          scopes: |
            github
            linter
            deps
            release
            other
            docs

          # Configure that a scope must always be provided.
          requireScope: false
          # The subject should not start with an uppercase character and should not end with a period.
          subjectPattern: ^(?![A-Z]).+[^.]$
          subjectPatternError: |
            The subject "{subject}" cannot start with an uppercase character or end with a period.

      - if: always() && (steps.lint_pr_title.outputs.error_message != null)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          message: |
            Thank you for opening this pull request.

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and
            it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Check if the PR contains scope
      - if: always() && (steps.lint_pr_title.scope == null)
        run: echo "::warning ::Scope for the PR is missed"

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true


